Loading workload...
Starting test.
Maximum execution time specified as: 2400 secs
 0 sec: 0 operations; 
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
 2 sec: 0 operations; 
 4 sec: 0 operations; 
 6 sec: 0 operations; 
 8 sec: 0 operations; 
 10 sec: 0 operations; 
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /172.31.27.106:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4bb9a3d0-68c9-11e4-a0f1-832ef99445b3; expected 4b5f27c0-68c9-11e4-a0f1-832ef99445b3)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:150)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:78)
	at com.yahoo.ycsb.ClientThread.run(Client.java:319)
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /172.31.27.106:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4bb9a3d0-68c9-11e4-a0f1-832ef99445b3; expected 4b5f27c0-68c9-11e4-a0f1-832ef99445b3)
	at com.datastax.driver.core.exceptions.DriverInternalError.copy(DriverInternalError.java:42)
	at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:256)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:172)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
	at com.yahoo.ycsb.db.CassandraCQLClient.createTable(CassandraCQLClient.java:168)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:144)
	... 2 more
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /172.31.27.106:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4bb9a3d0-68c9-11e4-a0f1-832ef99445b3; expected 4b5f27c0-68c9-11e4-a0f1-832ef99445b3)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:86)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:108)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:235)
	at com.datastax.driver.core.RequestHandler.onSet(RequestHandler.java:367)
	at com.datastax.driver.core.Connection$Dispatcher.messageReceived(Connection.java:582)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /172.31.27.106:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4bc47940-68c9-11e4-a0f1-832ef99445b3; expected 4b5f27c0-68c9-11e4-a0f1-832ef99445b3)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:150)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:78)
	at com.yahoo.ycsb.ClientThread.run(Client.java:319)
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /172.31.27.106:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4bc47940-68c9-11e4-a0f1-832ef99445b3; expected 4b5f27c0-68c9-11e4-a0f1-832ef99445b3)
	at com.datastax.driver.core.exceptions.DriverInternalError.copy(DriverInternalError.java:42)
	at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:256)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:172)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
	at com.yahoo.ycsb.db.CassandraCQLClient.createTable(CassandraCQLClient.java:168)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:144)
	... 2 more
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /172.31.27.106:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4bc47940-68c9-11e4-a0f1-832ef99445b3; expected 4b5f27c0-68c9-11e4-a0f1-832ef99445b3)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:86)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:108)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:235)
	at com.datastax.driver.core.RequestHandler.onSet(RequestHandler.java:367)
	at com.datastax.driver.core.Connection$Dispatcher.messageReceived(Connection.java:582)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
 12 sec: 0 operations; 
 14 sec: 0 operations; 
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /54.171.105.34:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4c841fc0-68c9-11e4-acf7-430554c66049; expected 4b5a6cd0-68c9-11e4-acf7-430554c66049)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:150)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:78)
	at com.yahoo.ycsb.ClientThread.run(Client.java:319)
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /54.171.105.34:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4c841fc0-68c9-11e4-acf7-430554c66049; expected 4b5a6cd0-68c9-11e4-acf7-430554c66049)
	at com.datastax.driver.core.exceptions.DriverInternalError.copy(DriverInternalError.java:42)
	at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:256)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:172)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
	at com.yahoo.ycsb.db.CassandraCQLClient.createTable(CassandraCQLClient.java:168)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:144)
	... 2 more
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /54.171.105.34:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4c841fc0-68c9-11e4-acf7-430554c66049; expected 4b5a6cd0-68c9-11e4-acf7-430554c66049)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:86)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:108)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:235)
	at com.datastax.driver.core.RequestHandler.onSet(RequestHandler.java:367)
	at com.datastax.driver.core.Connection$Dispatcher.messageReceived(Connection.java:582)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
 16 sec: 0 operations; 
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /54.171.105.34:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4c8494f0-68c9-11e4-acf7-430554c66049; expected 4b5a6cd0-68c9-11e4-acf7-430554c66049)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:150)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:78)
	at com.yahoo.ycsb.ClientThread.run(Client.java:319)
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /54.171.105.34:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4c8494f0-68c9-11e4-acf7-430554c66049; expected 4b5a6cd0-68c9-11e4-acf7-430554c66049)
	at com.datastax.driver.core.exceptions.DriverInternalError.copy(DriverInternalError.java:42)
	at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:256)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:172)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
	at com.yahoo.ycsb.db.CassandraCQLClient.createTable(CassandraCQLClient.java:168)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:144)
	... 2 more
Caused by: com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error occurred server side on /54.171.105.34:9042: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 4c8494f0-68c9-11e4-acf7-430554c66049; expected 4b5a6cd0-68c9-11e4-acf7-430554c66049)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:86)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:108)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:235)
	at com.datastax.driver.core.RequestHandler.onSet(RequestHandler.java:367)
	at com.datastax.driver.core.Connection$Dispatcher.messageReceived(Connection.java:582)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
 18 sec: 0 operations; 
 20 sec: 327 operations; 163.5 current ops/sec; [INSERT AverageLatency(us)=18981.67] 
 22 sec: 745 operations; 208.9 current ops/sec; [INSERT AverageLatency(us)=22816.36] [CLEANUP AverageLatency(us)=0.33] 
 24 sec: 979 operations; 117 current ops/sec; [INSERT AverageLatency(us)=15082.3] [CLEANUP AverageLatency(us)=0] 
Could not wait until max specified time, TerminatorThread interrupted.
 24 sec: 996 operations; 51.83 current ops/sec; [INSERT AverageLatency(us)=19776.35] [CLEANUP AverageLatency(us)=0] 
